require 'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "c",
    "lua",
    "query",
    "bash",
    "cmake",
    "comment",
    "commonlisp",
    "cpp",
    "disassembly",
    "dockerfile",
    "erlang",
    "fennel",
    "git_rebase",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "elixir",
    "heex",
    "eex",
    "graphql",
    "helm",
    "html",
    "http",
    "javascript",
    "json",
    "luadoc",
    "luap",
    "make",
    "markdown",
    "markdown_inline",
    "nasm",
    "php",
    "phpdoc",
    "proto",
    "regex",
    "rust",
    "sql",
    "starlark",
    "toml",
    "vim",
    "vimdoc",
    "xml",
  },
  -- ensure_installed = "all", -- install parsers for all supported languages
  sync_install = false,
  auto_install = true,
  additional_vim_regex_highlighting = false,
  highlight = { enable = true, },
  indent = { enable = true }
}
