require 'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "c",
    "lua",
    "query",
    "bash",
    "cmake",
    "comment",
    "commonlisp",
    "cpp",
    "disassembly",
    "dockerfile",
    "erlang",
    "fennel",
    "git_rebase",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "elixir",
    "heex",
    "eex",
    "graphql",
    "helm",
    "html",
    "http",
    "javascript",
    "json",
    "luadoc",
    "luap",
    "llvm",
    "make",
    "markdown",
    "markdown_inline",
    "nasm",
    "php",
    "phpdoc",
    "proto",
    "regex",
    "rust",
    "sql",
    "starlark",
    "toml",
    "vim",
    "vimdoc",
    "xml",
  }, -- only install parsers for elixir and heex
  -- ensure_installed = "all", -- install parsers for all supported languages
  sync_install = false,
  ignore_install = {},
  highlight = {
    enable = true,
    disable = {},
  },
}
